apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: alpine_wordpress
        imagePullPolicy: Never
        env:
        - name: WP_DB_NAME
          valueFrom:
            secretKeyRef:
              name: kubernetes-secret
              key: wp_db_name
        - name: WP_USER
          valueFrom:
            secretKeyRef:
              name: kubernetes-secret
              key: wp_user
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: kubernetes-secret
              key: wp_password
        - name: MYSQL_IP
          value: mysql-service.default.svc.cluster.local
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - /srcs/livenessprobe.sh
          initialDelaySeconds: 5
          periodSeconds: 3
        ports:
        - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  type: LoadBalancer
  ports:
  - name: wordpress
    port: 5050
    targetPort: 5050
    protocol: TCP
  selector:
    app: wordpress